branch-defaults:
  master:
    environment: imranariffin-login-pag
global:
  application_name: imranariffin-login-page
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
